[txtUML] adding the UUID project to txtUML-stdlib
ELTE-Soft/txtUML-stdlib pull request #1
Opened 2016-11-28 14:03 UTC by foudelsalhi

first upload of UUID project

2016-11-29 14:30 UTC, bmartin0121 commented on src/hu/elte/txtuml/stdlib/util/UUIDImplementation.java
> +	protected java.util.UUID getOrigUUID(Object val) {
What is the use of this function? Shouldn't this just return the `var` field of `this`?

2016-11-29 14:32 UTC, bmartin0121 commented on src/hu/elte/txtuml/stdlib/util/UUIDImplementation.java
> +		return var.equals(getOrigUUID(obj));
Why do you need `getOrigUUID` here?

2016-11-30 15:43 UTC, budaimartin requested changes
I re-checked your pull request. See my comments below.

2016-11-30 15:43 UTC, bmartin0121 commented on src/hu/elte/txtuml/stdlib/util/UUIDImplementation.java
> +	public boolean equals(Object obj) {
The `obj` parameter should be type `UUID` instead of `Object` because `Object` is not a txtUML class nor an external class.

2016-11-30 15:43 UTC, bmartin0121 commented on src/hu/elte/txtuml/stdlib/util/UUIDImplementation.java
> +	protected java.util.UUID getOrigUUID(Object val) {
What are you using this function for? Is it really needed?

2016-11-30 15:43 UTC, bmartin0121 commented on src/hu/elte/txtuml/stdlib/util/UUIDImplementation.java
> +		return var.compareTo(getOrigUUID(val));
Why don't use use `val.var` here?

2016-11-30 15:43 UTC, bmartin0121 commented on src/hu/elte/txtuml/stdlib/util/UUID.java
> +	 * public static UUID nameUUIDFromBytes(Collection<Byte> name) {
Why is this part of the code in comments?

2016-12-04 19:01 UTC, bmartin0121 commented
A student dicussed the use of the `getOrigUUID` function with @devaigergely81. You can use it but explain it in the Javadoc.

2016-12-04 20:27 UTC, foudelsalhi commented on src/hu/elte/txtuml/stdlib/util/UUID.java
> +	 * public static UUID nameUUIDFromBytes(Collection<Byte> name) {
we agreed that we will not implement that static method, I just commented it out instead of removing it from the interface...

2016-12-05 14:05 UTC, budaimartin approved these changes

2016-12-13 11:14 UTC, merged